export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const COMPANY_REQUEST = "COMPANY_REQUEST";
export const COMPANY_SUCCESS = "COMPANY_SUCCESS";
export const COMPANY_FAIL = "COMPANY_FAIL";

export const GET_COMPANY_DETAILS_REQUEST = "GET_COMPANY_DETAILS_REQUEST";
export const GET_COMPANY_DETAILS_SUCCESS = "GET_COMPANY_DETAILS_SUCCESS";
export const GET_COMPANY_DETAILS_FAIL = "GET_COMPANY_DETAILS_FAIL";

export const CREATE_COMPANY_REQUEST = "CREATE_COMPANY_REQUEST";
export const CREATE_COMPANY_SUCCESS = "CREATE_COMPANY_SUCCESS";
export const CREATE_COMPANY_FAIL = "REGISTER_USER_FAIL";

export const LOAD_COMPANY_REQUEST = "LOAD_COMPANY_REQUEST";
export const LOAD_COMPANY_SUCCESS = "LOAD_COMPANY_SUCCESS";
export const LOAD_COMPANY_FAIL = "LOAD_COMPANY_FAIL";


export const UPDATE_COMPANY_REQUEST = "UPDATE_COMPANY_REQUEST";
export const UPDATE_COMPANY_SUCCESS = "UPDATE_COMPANY_SUCCESS";
export const UPDATE_COMPANY_FAIL = "UPDATE_COMPANY_FAIL";


export const GET_COMPANIES_DETAILS_REQUEST = "GET_COMPANIES_DETAILS_REQUEST";
export const GET_COMPANIES_DETAILS_SUCCESS = "GET_COMPANIES_DETAILS_SUCCESS";
export const GET_COMPANIES_DETAILS_FAIL = "GET_COMPANIES_DETAILS_FAIL";

export const COMPANIES_REQUEST = "COMPANIES_REQUEST";
export const COMPANIES_SUCCESS = "COMPANIES_SUCCESS";
export const COMPANIES_FAIL = "COMPANIES_FAIL";

export const CREATE_COMPANIES_REQUEST = "CREATE_COMPANIES_REQUEST";
export const CREATE_COMPANIES_SUCCESS = "CREATE_COMPANIES_SUCCESS";
export const CREATE_COMPANIES_FAIL = "CREATE_COMPANIES_FAIL";

export const LOAD_COMPANIES_REQUEST = "LOAD_COMPANIES_REQUEST";
export const LOAD_COMPANIES_SUCCESS = "LOAD_COMPANIES_SUCCESS";
export const LOAD_COMPANIES_FAIL = "LOAD_COMPANIES_FAIL";

export const FILTER_COMPANIES_REQUEST = "FILTER_COMPANIES_REQUEST";
export const FILTER_COMPANIES_SUCCESS = "FILTER_COMPANIES_SUCCESS";
export const FILTER_COMPANIES_FAIL = "FILTER_COMPANIES_FAIL";
