export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const JOB_APPLICATION_REQUEST = "JOB_APPLICATION_REQUEST";
export const JOB_APPLICATION_SUCCESS = "JOB_APPLICATION_SUCCESS";
export const JOB_APPLICATION_FAIL = "JOB_APPLICATION_FAIL";

export const LOAD_JOB_APPLICATIONS_REQUEST = "LOAD_JOB_APPLICATIONS_REQUEST";
export const LOAD_JOB_APPLICATIONS_SUCCESS = "LOAD_JOB_APPLICATIONS_SUCCESS";
export const LOAD_JOB_APPLICATIONS_FAIL = "LOAD_JOB_APPLICATIONS_FAIL";

export const DELETE_JOB_APPLICATIONS_REQUEST = "DELETE_JOB_APPLICATIONS_REQUEST";
export const DELETE_JOB_APPLICATIONS_SUCCESS = "DELETE_JOB_APPLICATIONS_SUCCESS";
export const DELETE_JOB_APPLICATIONS_FAIL = "DELETE_JOB_APPLICATIONS_FAIL";

export const DELETE_JOB_APPLICATIONS_ID_REQUEST = "DELETE_JOB_APPLICATIONS_ID_REQUEST";
export const DELETE_JOB_APPLICATIONS_ID_SUCCESS = "DELETE_JOB_APPLICATIONS_ID_SUCCESS";
export const DELETE_JOB_APPLICATIONS_ID_FAIL = "DELETE_JOB_APPLICATIONS_ID_FAIL";

export const UPDATE_JOB_APPLICATIONS_REQUEST = "UPDATE_JOB_APPLICATIONS_REQUEST";
export const UPDATE_JOB_APPLICATIONS_SUCCESS = "UPDATE_JOB_APPLICATIONS_SUCCESS";
export const UPDATE_JOB_APPLICATIONS_FAIL = "UPDATE_JOB_APPLICATIONS_FAIL";

export const JOB_APPLICATIONS_REQUEST = "JOB_APPLICATIONS_REQUEST";
export const JOB_APPLICATIONS_SUCCESS = "JOB_APPLICATIONS_SUCCESS";
export const JOB_APPLICATIONS_FAIL = "JOB_APPLICATIONS_FAIL";

export const GET_JOB_APPLICATIONS_BY_COMPANY_NAME_REQUEST = "GET_JOB_APPLICATIONS_BY_COMPANY_NAME_REQUEST";
export const GET_JOB_APPLICATIONS_BY_COMPANY_NAME_SUCCESS = "GET_JOB_APPLICATIONS_BY_COMPANY_NAME_SUCCESS";
export const GET_JOB_APPLICATIONS_BY_COMPANY_NAME_FAIL = "GET_JOB_APPLICATIONS_BY_COMPANY_NAME_FAIL";

export const applicationsFilter = ["Application Status", "Jobs"];

export const ApplicationStatus = [
   "Closed",
   "Pending",
   "Shortlisted",
   "Rejected",
   "Offer Extended",
   "Offer Accepted",
   "Offer Declined"
];
export const updateEngineer = [
   "pending",
   "approved",
];
