export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const JOBS_REQUEST = "JOB_REQUEST";
export const JOBS_SUCCESS = "JOB_SUCCESS";
export const JOBS_FAIL = "JOB_FAIL";

export const JOB_REQUEST = "JOB_REQUEST";
export const JOB_SUCCESS = "JOB_SUCCESS";
export const JOB_FAIL = "JOB_FAIL";



export const DELETE_JOB_APPLICATIONS_REQUEST = "DELETE_JOB_APPLICATIONS_REQUEST";
export const DELETE_JOB_APPLICATIONS_SUCCESS = "DELETE_JOB_APPLICATIONS_SUCCESS";
export const DELETE_JOB_APPLICATIONS_FAIL = "DELETE_JOB_APPLICATIONS_FAIL";

export const CREATE_JOB_REQUEST = "CREATE_JOB_REQUEST";
export const CREATE_JOB_SUCCESS = "CREATE_JOB_SUCCESS";
export const CREATE_JOB_FAIL = "CREATE_JOB_FAIL";

export const UPDATE_JOB_REQUEST = "UPDATE_JOB_REQUEST";
export const UPDATE_JOB_SUCCESS = "UPDATE_JOB_SUCCESS";
export const UPDATE_JOB_FAIL = "UPDATE_JOB_FAIL";

export const LOAD_JOB_REQUEST = "LOAD_JOB_REQUEST";
export const LOAD_JOB_SUCCESS = "LOAD_JOB_SUCCESS";
export const LOAD_JOB_FAIL = "LOAD_JOB_FAIL";

export const LOAD_JOBS_REQUEST = "LOAD_JOBS_REQUEST";
export const LOAD_JOBS_SUCCESS = "LOAD_JOBS_SUCCESS";
export const LOAD_JOBS_FAIL = "LOAD_JOBS_FAIL";

export const GET_JOBS_REQUEST = "GET_JOBS_REQUEST";
export const GET_JOBS_SUCCESS = "GET_JOBS_SUCCESS";
export const GET_JOBS_FAIL = "GET_JOBS_FAIL";

export const APPLY_JOB_REQUEST = "APPLY_JOB_REQUEST";
export const APPLY_JOB_SUCCESS = "APPLY_JOB_SUCCESS";
export const APPLY_JOB_FAIL = "APPLY_JOB_FAIL";

export const DELETE_JOB_REQUEST = "DELETE_JOB_REQUEST";
export const DELETE_JOB_SUCCESS = "DELETE_JOB_SUCCESS";
export const DELETE_JOB_FAIL = "DELETE_JOB_FAIL";

export const JOB_STATUSES = [
   "open",
   "stopped",
   "closed",
];


