export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAIL = "LOGIN_FAIL";

export const REGISTER_USER_REQUEST = "REGISTER_USER_REQUEST";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAIL = "REGISTER_USER_FAIL";

export const UPDATE_USER_REQUEST = "UPDATE_USER_REQUEST";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_FAIL = "UPDATE_USER_FAIL";

export const UPDATE_ENGINEER_REQUEST = "UPDATE_ENGINEER_REQUEST";
export const UPDATE_ENGINEER_SUCCESS = "UPDATE_ENGINEER_SUCCESS";
export const UPDATE_ENGINEER_FAIL = "UPDATE_ENGINEER_FAIL";

export const LOAD_USER_REQUEST = "LOAD_USER_REQUEST";
export const LOAD_USER_SUCCESS = "LOAD_USER_SUCCESS";
export const LOAD_USER_FAIL = "LOAD_USER_FAIL";

export const DELETE_USER_REQUEST = "DELETE_USER_REQUEST";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_FAIL = "DELETE_USER_FAIL";

export const LOAD_ALL_STUDENTS_USER_REQUEST = "LOAD_ALL_STUDENTS_USER_REQUEST";
export const LOAD_ALL_STUDENTS_USER_SUCCESS = "LOAD_ALL_STUDENTS_USER_SUCCESS";
export const LOAD_ALL_STUDENTS_USER_FAIL = "LOAD_ALL_STUDENTS_USER_FAIL";

export const GET_ENGINEER_REQUEST = "GET_ENGINEER_REQUEST";
export const GET_ENGINEER_SUCCESS = "GET_ENGINEER_SUCCESS";
export const GET_ENGINEER_FAIL = "GET_ENGINEER_FAIL";

export const LOAD_ALL_ENGINEER_REQUEST = "LOAD_ALL_ENGINEER_REQUEST";
export const LOAD_ALL_ENGINEER_SUCCESS = "LOAD_ALL_ENGINEER_SUCCESS";
export const LOAD_ALL_ENGINEER_FAIL = "LOAD_ALL_ENGINEER_FAIL";


export const DELETE_ENGINEER_REQUEST = "DELETE_ENGINEER_REQUEST";
export const DELETE_ENGINEER_SUCCESS = "DELETE_ENGINEER_SUCCESS";
export const DELETE_ENGINEER_FAIL = "DELETE_ENGINEER_FAIL";

