name: Node.js CI

on:
  push:
    branches: [ "dev_cicd-1" ]
  pull_request:
    branches: [ "dev_cicd-1" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Build and test server
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: server/package-lock.json
    - run: |
        cd server
        npm install
        npm run test

    - name: Build and test client
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: client/package-lock.json
    - run: |
        cd client
        npm install
        npm run test
